name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  minimum_versions:
    strategy:
      matrix:
        python-version: ["3.8"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache multiple paths
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}
      - name: install-reqs
        run: python -m pip install --upgrade tox virtualenv setuptools pip -r requirements-dev.txt
      - name: install-modin
        run: python -m pip install pandas==2.0.0 polars==0.20.0
      - name: Run pytest
        run: pytest tests --cov=narwhals --cov=tests
      - name: Run doctests
        run: pytest narwhals --doctest-modules

  nightlies:
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache multiple paths
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}
      - name: install-reqs
        run: python -m pip install --upgrade tox virtualenv setuptools pip -r requirements-dev.txt
      - name: uninstall pandas
        run: python -m pip uninstall pandas -y
      - name: install-nightly
        run: python -m pip install --pre --extra-index https://pypi.anaconda.org/scientific-python-nightly-wheels/simple pandas
      - name: Run pytest
        run: pytest tests --cov=narwhals --cov=tests
      - name: Run doctests
        run: pytest narwhals --doctest-modules
